# Generated by Django 6.0.3 on 2026-03-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_name', models.CharField(help_text='The name of the island.', max_length=255)),
                ('island_description', models.TextField(help_text='A brief description of the island.')),
                ('sequence_in_journey', models.IntegerField(help_text='The order of the stop along the journey. (1=New York, 10=Dominica)', unique=True)),
            ],
            options={
                'ordering': ['sequence_in_journey'],
            },
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(default=1000, help_text='The amount of cash the player has.')),
                ('award_miles', models.IntegerField(default=0, help_text='The number of award miles the player has.')),
                ('morale', models.IntegerField(default=100, help_text='The morale level of the player.')),
                ('bugs', models.IntegerField(default=0, help_text='The number of bugs in the pitch project.')),
                ('days_remaining', models.IntegerField(default=30, help_text='The number of days remaining in the game challenge.')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.location')),
            ],
        ),
    ]
