# Generated by Django 5.2.13 on 2026-05-01 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameState",
        ),
    ]
