# Generated by Django 6.0.3 on 2026-03-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='island_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='island_name',
            new_name='name',
        ),
    ]
