# Generated by Django 5.2.13 on 2026-05-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_reportedissue"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="reward_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="location",
            name="reward_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="reward_resource",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morale", "Morale"),
                    ("cash", "Cash"),
                    ("award_miles", "Award Miles"),
                    ("bugs", "Bugs (Reduction)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="sequence_in_journey",
            field=models.IntegerField(
                help_text="Order of the stop (1=NYC, 10=Dominica)", unique=True
            ),
        ),
    ]
